# Generated by Django 5.1 on 2024-08-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Project_id", models.CharField(max_length=50)),
                ("Name", models.CharField(max_length=50)),
                ("Manager", models.CharField(max_length=50)),
                ("Customer", models.CharField(max_length=50)),
                ("City", models.CharField(max_length=50)),
                ("Start_Date", models.DateField()),
                ("End_Date", models.DateField()),
            ],
        ),
    ]
