# Generated by Django 5.1 on 2024-10-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfi',
            old_name='sent_by',
            new_name='assigned_to',
        ),
    ]
