# Generated by Django 5.1 on 2024-09-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Trinity_Project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
                ("assigned_to", models.CharField(max_length=50)),
                ("project_id", models.CharField(max_length=50)),
                ("due_date", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="Tasks",
        ),
    ]
