# Generated by Django 5.1 on 2024-10-02 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Trinity_Project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFI",
            fields=[
                ("date_received", models.DateField()),
                (
                    "RFI_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("sent_out_date", models.DateField()),
                ("type", models.CharField(max_length=50)),
                ("notes", models.TextField()),
                ("notes_closed", models.TextField()),
                ("description", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfi",
                        to="Trinity_Project.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
