# Generated by Django 5.1 on 2024-09-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='notes',
            new_name='description',
        ),
    ]
