# Generated by Django 5.1.2 on 2024-10-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfichangelog',
            old_name='user',
            new_name='assigned_to',
        ),
        migrations.AddField(
            model_name='rfichangelog',
            name='created_by',
            field=models.CharField(default='Test', max_length=50),
            preserve_default=False,
        ),
    ]
