# Generated by Django 5.1.2 on 2024-10-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='microsoft_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
