# Generated by Django 5.1 on 2024-10-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchangelog',
            name='project_id',
            field=models.CharField(max_length=100),
        ),
    ]
