# Generated by Django 5.1 on 2024-08-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
