# Generated by Django 5.1 on 2024-08-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='something', max_length=50),
            preserve_default=False,
        ),
    ]
