# Generated by Django 5.1 on 2024-09-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Trinity_Project", "0002_task_delete_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_id",
            field=models.CharField(default=1231, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
