# Generated by Django 5.1 on 2024-10-01 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0002_task_status_alter_submittal_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Trinity_Project.project'),
        ),
    ]
