# Generated by Django 5.1.2 on 2024-10-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0002_remove_user_microsoft_id_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Team Member', 'Team Member'), ('Administrator', 'Administrator'), ('Accountant', 'Accountant')], default='Team Member', max_length=50),
        ),
    ]
