# Generated by Django 5.1 on 2024-08-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='End_Date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Manager',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Project_id',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Start_Date',
            new_name='start_date',
        ),
    ]
