# Generated by Django 5.1 on 2024-10-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0002_rename_sent_by_rfi_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
