# Generated by Django 5.1 on 2024-08-19 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0003_rename_city_project_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='customer',
            new_name='current_manager',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='manager',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
    ]
