# Generated by Django 5.1.2 on 2024-10-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0003_invoice_project_name_alter_invoice_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='project_name',
        ),
    ]
