# Generated by Django 5.1.2 on 2024-10-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0003_alter_rfichangelog_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent')], max_length=20),
        ),
    ]
