# Generated by Django 5.1 on 2024-09-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0003_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
