# Generated by Django 5.1 on 2024-10-07 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0003_rfi_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 10, 7, 21, 56, 0, 564250, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcements',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7)),
        ),
    ]
