# Generated by Django 5.1 on 2024-09-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0004_alter_project_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='notes',
        ),
    ]
