# Generated by Django 5.1 on 2024-10-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Trinity_Project", "0004_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFIChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project", models.CharField(max_length=50)),
                ("date_received", models.CharField(max_length=50)),
                ("RFI_id", models.CharField(max_length=50)),
                ("sent_out_date", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("user", models.CharField(max_length=50)),
                ("notes", models.TextField()),
                ("notes_closed", models.TextField()),
                ("description", models.TextField()),
                ("changed_by", models.CharField(max_length=50)),
                ("change_time", models.DateField(auto_now_add=True)),
                ("change_description", models.TextField()),
            ],
        ),
    ]
