# Generated by Django 5.1 on 2024-10-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0004_announcements_created_at_announcements_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfi',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='rfi',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='submittal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
