# Generated by Django 5.1.2 on 2024-10-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0004_remove_invoice_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
