# Generated by Django 5.1 on 2024-10-08 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0005_remove_rfi_is_closed_rfi_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
