# Generated by Django 5.1.2 on 2024-10-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0005_invoice_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='project_name',
        ),
    ]
