# Generated by Django 5.1 on 2024-09-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0005_rename_description_project_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='folder_location',
            field=models.CharField(default='example', max_length=255),
            preserve_default=False,
        ),
    ]
