# Generated by Django 5.1 on 2024-10-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0006_task_completion_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=50),
        ),
    ]
