# Generated by Django 5.1 on 2024-09-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0006_project_folder_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
