# Generated by Django 5.1 on 2024-10-08 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0007_rfi_status_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfi',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='submittal',
            name='is_active',
        ),
    ]
