# Generated by Django 5.1 on 2024-10-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0008_remove_rfi_is_active_remove_submittal_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittal',
            name='closing_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submittal',
            name='send_email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submittal',
            name='sent_item',
            field=models.TextField(default=''),
        ),
    ]
