# Generated by Django 5.1 on 2024-09-16 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0009_alter_task_assigned_to_alter_task_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trinity_Project.project', to_field='project_id'),
        ),
    ]
