# Generated by Django 5.1 on 2024-10-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0009_submittal_closing_notes_submittal_send_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittal',
            name='closing_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='send_email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='sent_item',
            field=models.TextField(blank=True, default=''),
        ),
    ]
