# Generated by Django 5.1 on 2024-10-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0010_alter_submittal_closing_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfi',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='notes_closed',
            field=models.TextField(blank=True, default=''),
        ),
    ]
