# Generated by Django 5.1 on 2024-09-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trinity_Project', '0011_alter_project_manager_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.CharField(max_length=50),
        ),
    ]
